[package]
name = "tikv-client"
version = "0.0.0"
keywords = ["TiKV", "KV", "distributed-systems"]
license = "Apache-2.0"
authors = ["The TiKV Project Authors"]
repository = "https://github.com/tikv/client-rust"
description = "The rust language implementation of TiKV client."
edition = "2018"

[features]
default = []
# Enable integration tests with a running TiKV and PD instance.
# Use $PD_ADDRS, comma separated, to set the addresses the tests use. 
integration-tests = []

[lib]
name = "tikv_client"

[dependencies]
regex = "1"
derive-new = "0.5"
failure = "0.1"
futures-preview = { version = "0.3.0-alpha.15", features = ["compat"] }
grpcio = { version = "0.5.0-alpha", features = [ "secure", "prost-codec" ], default-features = false }
lazy_static = "1"
log = "0.3.9"
serde = "1.0"
serde_derive = "1.0"
tokio-core = "0.1"
tokio-timer = "0.2"
bytes = "0.4"
async-trait = "0.1.3"

[dependencies.kvproto]
git = "https://github.com/pingcap/kvproto.git"

[dependencies.prometheus]
version = "0.4.2"
default-features = false
features = ["push", "process"]

[dev-dependencies]
clap = "2.32"
tempdir = "0.3"
runtime = "0.3.0-alpha.3"
runtime-tokio = "0.3.0-alpha.3"
proptest = "0.9"
proptest-derive = "0.1.0"

[replace]
"prost:0.5.0" = { git = "https://github.com/danburkert/prost", rev = "1944c27c3029d01ff216e7b126d846b6cf8c7d77" }
